const truthBasePrompts = [
  "Who is your most random Bollywood crush that your friends would roast you for?",
  "Who is your most random Hollywood crush that you would still defend loudly?",
  "Which singer is such a dangerous crush for you that one live clip is enough?",
  "Which fictional character made you understand your type a little too well?",
  "What is the most delulu thought you have had after one good conversation?",
  "What is the most simp thing you have done but still act cool about?",
  "If your ex came back with a full filmy apology, what would your first reaction be?",
  "Have you ever acted chill after getting a reply and then smiled at the wall?",
  "What is the pettiest reason you lost interest in someone attractive?",
  "What is one green flag that makes you fold faster than it should?",
  "What is one red flag you would never tolerate now, no matter how hot the person is?",
  "What is your most toxic but funny standard in crush mode?",
  "What is your biggest turn-off in texting?",
  "What is your biggest weakness when you are trying to act nonchalant?",
  "What is a type you pretend you do not have but definitely have?",
  "Which kind of voice would ruin your decision-making instantly?",
  "Have you ever liked the attention more than the actual person?",
  "Would you reply if your ex texted you at 1 a.m. with \"can we talk\"?",
  "What is your most embarrassing crush era ever?",
  "Which emoji exposes you the fastest when you like someone?",
  "Would you rather be chased, or do you secretly enjoy chasing?",
  "What is the most random thing that gives you butterflies?",
  "What is the hardest first message for you to send without overthinking?",
  "Who was your first proper celebrity crush and why were you down bad?",
  "What is the most dramatic thing you have done because of a dry reply?",
  "What is one thing people always misunderstand about your type?",
  "What is your honest opinion on situationships?",
  "What is your most harmless red-flag behavior in crush mode?",
  "Which song on your playlist exposes your soft side immediately?",
  "Which trend do you pretend to hate but low-key enjoy?",
  "Which movie couple looks cute on screen but would exhaust you in real life?",
  "Which reality show would expose your worst traits in one episode?",
  "Which app knows your mood swings better than your friends do?",
  "What is a very specific compliment that would work on you every single time?",
  "Which friend in your group has the most questionable taste in crushes?",
  "What is one thing you would never post but would definitely stalk?",
  "What is the strongest first-impression move someone can pull on you?",
  "What is one thing you miss about old-school crushes before reels and seen-zones?",
  "Which Bollywood song would perfectly describe your current love life chaos?",
  "Which singer could fix your mood even if the rest of the day was trash?",
  "Which celebrity opinion of yours would get you cancelled in your own group chat?",
  "What is one habit that instantly makes someone cooler in your eyes?",
  "What is a date idea you defend even if everyone calls it basic?",
  "What is one thing you pretend not to care about but definitely track?",
  "What is the funniest excuse you have used to dodge someone?",
  "If your current mood had a playlist title, what would it be?",
  "What is the most confusing mixed signal you still remember clearly?",
  "Have you ever fallen for potential more than the actual person?",
  "What is one thing an ex taught you that you still use now?",
  "Which celebrity is attractive but still not your type at all?",
  "What is your most judgmental take about dry texters?",
  "What is one thing that can turn a normal person into your crush very fast?",
  "What is the most shameless thing you have done after seeing someone post a fire picture?",
  "Which type of Instagram story are you opening first, no matter what?",
  "Who is your safest celebrity crush answer, and who is your real answer?",
  "What is one line someone said to you that still lives in your head rent-free?",
  "What is the biggest clown move you have made in the name of attraction?",
  "Which ex, crush, or talking stage would your friends ban you from revisiting?",
  "What is one thing that makes you instantly go, bhai no chance?",
  "What is one thing that makes you instantly go, okay I am listening?",
];

const dareBasePrompts = [
  "Reveal your most random Bollywood crush and defend it like your reputation depends on it.",
  "Reveal your most random Hollywood crush and give one solid reason.",
  "Name your current singer crush in your most serious courtroom voice.",
  "Act like your crush liked a picture from two years ago.",
  "Pretend your ex texted \"hey stranger\" and react for 10 seconds.",
  "Draft a clean flirty IG reply in one line.",
  "Say your smoothest one-liner with full fake confidence.",
  "Describe your type using only five words.",
  "Rate your own rizz out of 10 and defend the number.",
  "Do your best \"I totally do not care\" face for 15 seconds.",
  "Pitch yourself like a slightly delulu dating bio.",
  "Say one green flag, one red flag, and one yellow flag without pausing.",
  "Do a dramatic reaction to a dry \"hmm\" reply.",
  "Reveal the pettiest reason you would remove someone from your close-friends list.",
  "Pretend you are rejecting a dry texter politely but savagely.",
  "Describe your ideal first date like a Bollywood trailer.",
  "Give a fake award speech for best taste in crushes.",
  "Show the emoji you would send to a risky late-night story reply.",
  "Do your best \"I was not stalking, it just opened\" excuse.",
  "Introduce your celebrity crush like a gossip-page anchor.",
  "Make a seven-word caption for a suspiciously soft launch post.",
  "Say whether you fold faster for eyes, humor, voice, or attention.",
  "Act like your favorite singer just replied to your message.",
  "Give a clean roast to people who leave others on seen for fun.",
  "Narrate your crush life like a cricket commentator.",
  "Describe your current mood like a dramatic movie title.",
  "Give a fake award acceptance speech for most delulu person here.",
  "Name eight actors or singers in 20 seconds.",
  "Speak only in questions for 30 seconds.",
  "Act like a reality-show host exposing your own taste in crushes.",
  "Explain your weekend in exactly nine words.",
  "Do your best villain laugh after reading a bad text.",
  "Speak like a news anchor describing your group chat chaos.",
  "Describe your vibe like a streaming-show title.",
  "Do a dramatic weather report for your love life this week.",
  "Name six movies you would rewatch forever.",
  "Explain your favorite song without naming it.",
  "Give a one-line TED Talk title for your emotional damage.",
  "Pretend your chair is a throne and celebrate being the problem.",
  "Give a trailer-voice intro for your next sentence.",
  "Name seven emojis you overuse in 15 seconds.",
  "Act like you just won an award for best fake nonchalance.",
  "Describe your last week using only song titles.",
  "Do a fake red-carpet interview with yourself.",
  "Talk like a podcast host for 30 seconds about your bad choices.",
  "Give a serious review of your favorite comfort snack.",
  "Do a confidence walk like you just got the reply you wanted.",
  "Explain your vibe in exactly seven words.",
  "Act like your phone is exposing all your crush history.",
  "Give a dramatic countdown from 10 and freeze like a serial overthinker.",
  "Choose Bollywood crush or singer crush and fight for your answer.",
  "Say one line that sounds flirty but stays clean.",
  "Act like your friends caught you zooming into someone's story.",
  "Describe your group chat role in one savage sentence.",
  "Do a fake apology to your ex like a soap-opera character.",
  "Give your type a shaadi-bio style intro in one line.",
  "Roast your own taste in crushes for 10 seconds.",
  "Pretend you are too cool for love and fail badly for 15 seconds.",
  "Announce your red flag weakness like breaking news.",
  "Give a filmy monologue about being left on delivered.",
];

const truthTemplates = [
  {
    pattern: "Who is your current {category} crush that would make your group chat pause for a second?",
    tokens: {
      category: [
        "Bollywood actor",
        "Bollywood actress",
        "Hollywood actor",
        "Hollywood actress",
        "singer",
        "rapper",
        "fictional character",
        "influencer",
      ],
    },
  },
  {
    pattern: "What is one {trait} thing that instantly gets your attention in {context}?",
    tokens: {
      trait: [
        "tiny",
        "unexpected",
        "non-physical",
        "green-flag",
        "low-key",
        "style-related",
        "confident",
        "soft-spoken",
      ],
      context: [
        "real life",
        "Instagram",
        "a first chat",
        "a group setting",
        "a late-night conversation",
        "a first meeting",
      ],
    },
  },
  {
    pattern: "What is one {adj} texting move that works on you way too fast?",
    tokens: {
      adj: [
        "clean",
        "funny",
        "confident",
        "subtle",
        "slightly flirty",
        "low-key caring",
        "smooth",
      ],
    },
  },
  {
    pattern: "How do you usually act when your {person} {action}?",
    tokens: {
      person: ["crush", "ex", "favorite person", "old talking stage", "celebrity crush"],
      action: [
        "texts first",
        "posts a fire picture",
        "acts distant",
        "suddenly gives you attention",
        "ignores your message",
        "shows up online out of nowhere",
      ],
    },
  },
  {
    pattern: "Which matters more to you in a person: {qualityA} or {qualityB}?",
    tokens: {
      qualityA: ["humor", "consistency", "looks", "voice", "ambition", "fashion sense", "effort"],
      qualityB: ["kindness", "confidence", "mystery", "softness", "loyalty", "smart banter", "patience"],
    },
  },
  {
    pattern: "What is your honest opinion on {topic} when it comes to {context}?",
    tokens: {
      topic: [
        "situationships",
        "double texting",
        "story replies",
        "soft launches",
        "late-night chats",
        "mixed signals",
        "friends-to-lovers arcs",
      ],
      context: [
        "real life",
        "online flirting",
        "friend groups",
        "your own habits",
        "today's dating scene",
        "modern talking stages",
      ],
    },
  },
  {
    pattern: "What is one thing your {person} taught you about {lesson}?",
    tokens: {
      person: ["ex", "old crush", "last relationship", "last talking stage", "favorite person"],
      lesson: ["trust", "patience", "texting", "standards", "timing", "communication", "self-respect"],
    },
  },
  {
    pattern: "Which {topic} opinion would get you judged by your friends instantly?",
    tokens: {
      topic: [
        "Bollywood",
        "Hollywood",
        "singer ranking",
        "reality show",
        "rom-com",
        "playlist",
        "celebrity couple",
        "main-character",
        "reel culture",
      ],
    },
  },
  {
    pattern: "What is your most {adj} habit during {context}?",
    tokens: {
      adj: ["random", "dramatic", "chaotic", "funny", "specific", "petty", "delulu"],
      context: [
        "group chats",
        "late-night scrolling",
        "crush mode",
        "movie watching",
        "playlist making",
        "weekend plans",
      ],
    },
  },
  {
    pattern: "Which {media} could you defend forever even if nobody agrees?",
    tokens: {
      media: [
        "movie",
        "song",
        "singer",
        "actor",
        "web series",
        "reality show",
        "celebrity pair",
        "album",
        "Bollywood era",
      ],
    },
  },
  {
    pattern: "What is your most savage take about {topic}?",
    tokens: {
      topic: [
        "dry texters",
        "seen-zoners",
        "fake nonchalance",
        "celeb crush answers",
        "soft launches",
        "group chat detectives",
        "people who say they hate love",
      ],
    },
  },
];

const dareTemplates = [
  {
    pattern: "Give a {style} intro for your {category} crush in {duration}.",
    tokens: {
      style: [
        "dramatic",
        "serious",
        "Bollywood trailer",
        "rom-com",
        "award-show",
        "cricket-commentary",
        "whispered",
        "podcast",
      ],
      category: ["Bollywood", "Hollywood", "singer", "fictional", "influencer", "athlete"],
      duration: ["10 seconds", "15 seconds", "20 seconds"],
    },
  },
  {
    pattern: "Act like your {person} just {action} for {duration}.",
    tokens: {
      person: ["crush", "ex", "favorite singer", "celebrity crush", "old talking stage"],
      action: [
        "texted you first",
        "liked your story",
        "left you on seen",
        "posted a glow-up picture",
        "said they miss you",
        "sent a voice note",
      ],
      duration: ["10 seconds", "15 seconds", "20 seconds"],
    },
  },
  {
    pattern: "Drop a {tone} one-liner you would use in {platform}.",
    tokens: {
      tone: ["smooth", "shy", "funny", "bold", "dramatic", "soft", "delulu", "main-character"],
      platform: ["a story reply", "an Instagram DM", "a late-night chat", "the comment section", "a voice note", "a first reply"],
    },
  },
  {
    pattern: "Reveal your {topic} in exactly {count} words.",
    tokens: {
      topic: [
        "type",
        "green flag",
        "red flag",
        "celebrity crush take",
        "biggest weakness",
        "ideal date",
        "worst mixed signal",
        "most delulu habit",
      ],
      count: ["4", "5", "6", "7", "8"],
    },
  },
  {
    pattern: "Choose between {optionA} and {optionB}, then defend it like your group chat is judging you.",
    tokens: {
      optionA: [
        "Bollywood crush",
        "Hollywood crush",
        "singer crush",
        "fictional crush",
        "eye contact",
        "voice",
        "humor",
        "consistency",
      ],
      optionB: [
        "singer crush",
        "fictional crush",
        "soft texting",
        "late-night honesty",
        "looks",
        "loyalty",
        "confidence",
        "mystery",
      ],
    },
  },
  {
    pattern: "Pretend you are a {role} and explain your {topic} in {duration}.",
    tokens: {
      role: ["dating coach", "radio host", "Bollywood hero", "rom-com narrator", "relationship judge", "nosy bestie", "nosy auntie"],
      topic: ["type", "crush taste", "worst weakness", "best green flag", "most chaotic standard", "celebrity ranking"],
      duration: ["15 seconds", "20 seconds", "30 seconds"],
    },
  },
  {
    pattern: "Say {count} things that make someone attractive without repeating any word.",
    tokens: {
      count: ["4", "5", "6", "7"],
    },
  },
  {
    pattern: "Do a {challenge} challenge, then reveal your {topic}.",
    tokens: {
      challenge: ["no-smile", "straight-face", "dramatic pause", "no-filler-word", "slow-clap", "whisper", "fake-cool"],
      topic: ["celebrity crush", "type", "red flag weakness", "most toxic standard", "best green flag"],
    },
  },
  {
    pattern: "Describe your {topic} in exactly {count} words.",
    tokens: {
      topic: ["mood", "weekend", "playlist vibe", "group chat energy", "movie taste", "dream vacation", "love life mess"],
      count: ["5", "6", "7", "8", "9"],
    },
  },
  {
    pattern: "Give a {style} mini speech about {topic}.",
    tokens: {
      style: ["savage", "filmy", "overdramatic", "anchor-style", "coach-style", "fully delulu"],
      topic: [
        "being left on delivered",
        "your crush taste",
        "your red flag weakness",
        "why dry texters are a problem",
        "why your group chat never supports you",
      ],
    },
  },
];

const truthMatrix = {
  crushCategories: [
    "Bollywood crush",
    "Hollywood crush",
    "singer crush",
    "fictional crush",
    "influencer crush",
    "athlete crush",
  ],
  crushAngles: [
    "right now",
    "that your friends would clown you for",
    "that you can defend seriously",
    "that changed recently",
    "that is not the obvious answer",
    "that says too much about your type",
  ],
  attentionHooks: [
    "good voice notes",
    "unexpected kindness",
    "strong eye contact",
    "effortless humor",
    "clean fashion sense",
    "smart banter",
    "consistent replies",
    "soft teasing",
    "main-character energy",
    "protective energy",
  ],
  attentionContexts: [
    "in real life",
    "on Instagram",
    "in group chats",
    "in late-night chats",
    "during a first meeting",
    "when you are trying to act chill",
  ],
  scenarios: [
    "your ex texted \"I miss you\"",
    "your crush liked your old photo",
    "someone hot replied to your story",
    "a celebrity you love followed you",
    "your old talking stage suddenly returned",
    "the person you like started acting distant",
  ],
  comparisons: [
    { left: "humor", right: "looks" },
    { left: "voice", right: "eye contact" },
    { left: "consistency", right: "mystery" },
    { left: "softness", right: "confidence" },
    { left: "fashion sense", right: "smart banter" },
    { left: "late-night honesty", right: "daytime effort" },
  ],
  opinionTopics: [
    "double texting",
    "story replies",
    "soft launches",
    "situationships",
    "mixed signals",
    "celebrity couple hype",
    "friend-zone comebacks",
    "late-night chats",
  ],
  opinionContexts: [
    "right now",
    "overall",
    "on social media",
    "in real life",
    "these days",
    "inside your group chat",
  ],
  behaviors: [
    "hidden a crush for months",
    "acted unbothered while overthinking badly",
    "checked a profile more times than needed",
    "fallen for attention more than the person",
    "let a red flag slide because the face card was strong",
    "re-read an old chat just for the feeling",
  ],
  popCultureTopics: [
    "movie couples",
    "singer rankings",
    "reality shows",
    "celebrity glow-ups",
    "playlist moods",
    "rom-com endings",
    "fan wars",
    "web-series red flags",
  ],
};

const dareMatrix = {
  revealTopics: [
    "most random Bollywood crush",
    "most random Hollywood crush",
    "current singer crush",
    "real type",
    "best green flag",
    "worst red flag",
    "dating bio",
    "soft launch caption",
  ],
  reactionScenarios: [
    "your crush just texted first",
    "your ex just posted a glow-up",
    "your favorite singer just replied",
    "you got caught stalking a profile",
    "you saw a dry \"hmm\" reply",
    "someone sent you mixed signals again",
  ],
  platforms: ["story reply", "Instagram DM", "comment section", "late-night text", "voice note", "first chat"],
  tones: ["smooth", "funny", "bold", "soft", "dramatic", "main-character", "serious", "slightly delulu"],
  personas: ["Bollywood hero", "award-show host", "radio jockey", "rom-com narrator", "cricket commentator", "gossip-page admin"],
  choices: [
    { left: "Bollywood crush", right: "Hollywood crush" },
    { left: "singer crush", right: "fictional crush" },
    { left: "eye contact", right: "voice" },
    { left: "humor", right: "consistency" },
    { left: "soft texting", right: "late-night honesty" },
    { left: "looks", right: "loyalty" },
  ],
  generalActs: [
    "a movie-trailer intro",
    "a dramatic weather report",
    "a fake award speech",
    "a fake red-carpet interview",
    "a reality-show intro",
    "a news-anchor update",
    "a podcast opening",
    "a villain laugh",
  ],
  durations: ["10 seconds", "15 seconds", "20 seconds", "30 seconds"],
};

module.exports = {
  truthBasePrompts,
  dareBasePrompts,
  truthTemplates,
  dareTemplates,
  truthMatrix,
  dareMatrix,
};
